# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4fcf48bf09f35a87a18d058a6e083ebd968ab26143c4f4c56089e11cce83d00ebf95e8327323bc1390f59612f6b2c20054649f0eee0b45eaaf735c2510960dc

test:
  secret_key_base: 0e02fa835a7a8846eb963202e2facc07835b6fe22f37c8b75c30b489c4bd654e5d15999410cba13691f77ba07da8fd012a2d35d321e5849bb01fd971bc51e609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
